Iter5
romanmendelproject/go-yandex-metrics pull request #5
Opened 2024-06-11 19:37 UTC by romanmendelproject

2024-06-14 18:43 UTC, capsulated requested changes
В общем всё хорошо, компактный и лаконичный код. Есть замечания по структуре, написал в коментах. Немного привыкнуть с синтаксису и особенностям языка - и будет пушка

2024-06-14 18:43 UTC, capsulated commented on cmd/agent/main.go
> +			err := metrics.Update()
`metrics.Update` на 19 строке и `updateMetrics(&metrics)` на 25 строке 🤔 Явно что-то нужно переименовать

2024-06-14 18:43 UTC, capsulated commented on cmd/agent/main.go
> +			panic(err)
Приложение остановится, если не получится обновить метрику? В рантайме так лучше не делать, максимум при инициализации. А в такие случаи просто логировать и выводить сообщение об ошибке

2024-06-14 18:43 UTC, capsulated commented on cmd/agent/main.go
> +func updateMetrics(m *Metrics) {
Для реализации воркера  метриками необходимо создать отдельный пакет (сервисный слой) и убрать из пакета `cmd`, так как в нём должна быть только инициализация и запуск волркеров с конфигом

2024-06-14 18:43 UTC, capsulated commented on cmd/agent/metrics.go
> +	Value interface{}
Универсальность в данном случае наоборот только усложняет логику. Можно просто описать две мапы метрик float и int - самый удобный вариант. Если можно не тратить память и процессор на конвертацию, почему бы и не описать объекты. Пустой интерфейс - это аналог `any` из других языков, а `any` как известно, использовать - плохая практика

2024-06-14 18:43 UTC, capsulated commented on cmd/server/handlers/handlers.go
> +func UpdateGauge(storage storage.Storage) http.HandlerFunc {
Передача зависимости через параметр неудобно тем, что когда станет много методов, то зависимостями управлять станет больно.

Для хендлеров можно создать объект. Это стандартное управления зависимостями (DI) в go (пример):

```go
type MemStorage struct { .... }
func NewMemStorgage(...) ...
func (ms *MemStorage) Create(key string, val string) error { ... }
func (ms *MemStorage) Read(key string) ([]string, error) { ... }

// Хендлеры
type Storer interface {
   Create(key string, val string) error
   Read(key string) ([]string, error)
}

type ServiceHandlers struct {
   store Storer
}

func NewHandlers(store Storer) *Handlers {
   ...
   return &Handlers{
      store: store
   }
}

func (h *Handlers) someHandler(w http.ResponseWriter, r *http.Request) { 
   h.store.Create(...)
   ...
}

type MetricHandler interface ...

type Router struct {
   handlers MetricHandler
}

func NewRouter(handlers Handler) *Router {
	...
	r.Post("/getID", handlers.someHandler)
	r.Get("/", handlers.someHandler)
	...
}
```

2024-06-14 18:43 UTC, capsulated commented on cmd/server/handlers/utils.go
> +type URLParamsValue struct {
Можно `встраивание` использовать в данном случае. Немного смущают почти одинаковые типы 🤔 Мне кажется, можно как-то упростить

2024-06-14 18:43 UTC, capsulated commented on cmd/server/main.go
> +	r.Route("/value", func(r chi.Router) {
Как прокинуть зависимости написал в сниппете выше.

2024-06-14 18:43 UTC, capsulated commented on cmd/server/main.go
> +	r.Route("/value", func(r chi.Router) {
Из cmd также необходимо функционал убрать по пакетам: роутер, хендлеры, хранилка. А в cmd вызов коснтуркторов и старт приложения с конфигом

2024-06-14 18:43 UTC, capsulated commented on cmd/server/storage/storage.go
> +func InitMemStorage() MemStorage {
Старнартный конструктор, именуется по [рекомендациям комьюнити](https://go.dev/doc/effective_go#interface-names):
```go
func NewMemStorage() *MemStorage { ... }
```
И возвращают указатель на экземпляр. 

Вопрос: когда лучше возвращать указатель, а когда значение?

2024-06-14 18:43 UTC, capsulated commented on cmd/server/storage/storage.go
> +type Storage interface {
Интерфейс принято описывать в месте использования, а не в месте реализации

2024-06-16 07:03 UTC, romanmendelproject commented on cmd/agent/main.go
> +			panic(err)
Нужно ли в таком случае прокидывать ошибку наверх, у меня недопонимания в каких случаях можно прокинуть ошибку, а в каких делать это не обязательно?

2024-06-16 17:28 UTC, romanmendelproject commented on cmd/server/storage/storage.go
> +func InitMemStorage() MemStorage {
Указатель думаю лучше возвращать, если в структуру будут в дальнейшем вносится изменения.

2024-06-16 17:30 UTC, romanmendelproject commented on cmd/agent/metrics.go
> +	Value interface{}
А если у меня потом появится еще один тип, кроме int64 и float64?

2024-06-17 21:03 UTC, capsulated commented on cmd/agent/main.go
> +			err := metrics.Update()
👍

2024-06-17 21:03 UTC, capsulated commented on cmd/agent/main.go
> +			panic(err)
С паникой - критикал  замечание, если решил оставить, то должны быть веские аргументы

2024-06-17 21:07 UTC, capsulated commented on cmd/agent/metrics.go
> +	Value interface{}
Так можно посмотреть все метрики пакета.

Но принципе, пустой интерфейс - это самый гибкий вариант. Но с гибкостью больше проблем и больше ресурсов (при приведении типов). Поэтому кодогенерация перед билдом в таким случаях - идеально. Но только в случае, нагрузка растёт. В  не нагруженных сервисах это незначительно

2024-06-17 21:20 UTC, capsulated approved these changes
Да, всё круто!

По пакетам, пару пунктов справочной инфы: 
- Внутри `internal` могут быть пакеты, которые общие для `agent` и `server`
- Можно и по-другому организовывать структуру пактов (можно в internal): скажем, пакет `server`, то есть, папка, в которой много файлов с описанием нескольких типов: Handlers, Router, HttpServer с конструкторами. Далее, папка `config` (с двумя типами конфигов), также `storage`, `report` (из прошлого пункта) и `metric` (как домен/модель) и всё это в корне `internal`

Я это пишу, чтобы был понятен принцип. И в следующем спринте можно переделать структуру пакетов, если будет необходимость, смотри по собственному усмотрению, а на ревью посмотрим, если что

2024-06-20 20:41 UTC, merged